name: publish
on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Connect to Azure Container registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Container build and push to a Azure Container registry (ACR)
      - run: |
          docker build -f Dockerfile -t ${{ env.REGISTRY_NAME }}.azurecr.io/argo-controller:${{ github.sha }} .
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/argo-controller:${{ github.sha }}

      # Scan image for vulnerabilities
      - uses: Azure/container-scan@v0
        with:
          image-name: ${{ env.REGISTRY_NAME }}.azurecr.io/argo-controller:${{ github.sha }}
          severity-threshold: CRITICAL
          run-quality-checks: false
